In [2]:
import numpy as np
from time import process_time

In [3]:
## normal list speed

python_list = [i for i in range(1000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.0


In [4]:
### numpy list

np_array = np.array([i for i in range(1000)])
start_time = process_time()
np_array = np_array + 5
end_time = process_time()
print(end_time - start_time)

0.0


In [5]:
## numpy arrays 

list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [6]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [7]:
## Creating a 1 DIM array

a = np.array([1,2,3,4,5])
a.shape

(5,)

In [8]:
## 2 rows , 4 cols

b = np.array([(1,2,3,4,5) , (6,7,8,9,10)])
print(b)
b.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [12]:
### Float data

c = np.array([(1,2,3,5,4) , (6,7,8,9,10)] , dtype=float)
print(c)

[[ 1.  2.  3.  5.  4.]
 [ 6.  7.  8.  9. 10.]]


In [13]:
### Create a numpy arrays of 0's

x = np.zeros( (4,5) )
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
### create numpy array of 1's

y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
## array of a particular value 

z = np.full( (5,4) , 5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [16]:
### create a identity matrix

a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
## numpy array with random value 

b = np.random.random((3,4))
print(b)

[[0.91984336 0.37507373 0.98686494 0.15968603]
 [0.24925479 0.50447658 0.02694826 0.22400273]
 [0.66209363 0.46538524 0.71106322 0.09941792]]


In [18]:
## random intger value within specific range with count

c = np.random.randint(10,100,(3,5))
print(c)

[[25 28 70 30 33]
 [73 56 28 53 10]
 [89 41 83 89 21]]
